Repository boostcampwm2023/iOS05-Village, pull requests merged in 2024-01, with the labels that each got.

#587 [iOS/#584] 홈 화면 Clean Architecture 도입
  iOS/Village/Village.xcodeproj/project.pbxproj
  iOS/Village/Village/Common/PostType.swift
  iOS/Village/Village/Data/Network/APIEndPoints.swift
  iOS/Village/Village/Data/Network/DTO/PostListRequestDTO.swift
  iOS/Village/Village/Data/Network/DTO/PostListResponseDTO.swift
  iOS/Village/Village/Data/Repository/DefaultPostListRepository.swift
  iOS/Village/Village/Domain/Entity/PostListItem.swift
  iOS/Village/Village/Domain/Repository/PostListRepository.swift
  iOS/Village/Village/Domain/UseCase/PostListUseCase.swift
  iOS/Village/Village/Domain/UseCase/Protocol/UseCase.swift
  iOS/Village/Village/Network/APIProvider/NetworkAPI.swift
  iOS/Village/Village/Presentation/Commons/Cell/RentPostTableViewCell.swift
  iOS/Village/Village/Presentation/Commons/Cell/RequstPostTableViewCell.swift
  iOS/Village/Village/Presentation/Home/View/HomeViewController.swift
  iOS/Village/Village/Presentation/Home/ViewModel/HomeViewModel.swift
  iOS/Village/Village/Presentation/MyPosts/View/MyPostsViewController.swift
  iOS/Village/Village/Presentation/MyPosts/ViewModel/MyPostsViewModel.swift
  iOS/Village/Village/Presentation/SearchResult/View/SearchRentTableViewCell.swift
  iOS/Village/Village/Presentation/SearchResult/View/SearchRequstTableViewCell.swift
  iOS/Village/Village/Presentation/SearchResult/View/SearchResultViewController.swift
  iOS/Village/Village/Presentation/SearchResult/ViewModel/SearchResultViewModel.swift
Labels: enhancement, iOS, post-list

#592 [iOS/#591] Network Layer Combine을 사용할 수 있도록 수정
  iOS/Village/Village.xcodeproj/project.pbxproj
  iOS/Village/Village/Network/APIProvider/CombineAuthInterceptor.swift
  iOS/Village/Village/Network/APIProvider/NetworkAPI.swift
  iOS/Village/Village/Network/APIProvider/NetworkService.swift
Labels: enhancement, iOS, environment

#595 [BE/#593] post service 테스트 코드 작성
  BE/src/post/post.service.spec.ts
  BE/src/post/post.service.ts
Labels: BE, environment

#601 [BE/#600] 나간 채팅방 상대가 재전송시 뜨게하기
  BE/.gitignore
  BE/src/chat/chat.controller.ts
  BE/src/chat/chat.service.ts
  BE/src/chat/chats.gateway.ts
  BE/src/entities/chatRoom.entity.ts
Labels: review, BE, chatting

#602 [BE/#576] 마지막 채팅 DB 에 함께 저장
  BE/src/chat/chat.service.ts
  BE/src/entities/chatRoom.entity.ts
Labels: review, BE, chatting

#596 [iOS/#594] 채팅목록 Clean Architecture 도입
  iOS/Village/Village.xcodeproj/project.pbxproj
  iOS/Village/Village/Data/Network/APIEndPoints.swift
  iOS/Village/Village/Data/Network/DTO/ChatListItemDTO.swift
  iOS/Village/Village/Data/Network/DTO/ChatListResponseDTO.swift
  iOS/Village/Village/Data/Repository/DefaultChatListRepository.swift
  iOS/Village/Village/Domain/Entity/ChatList.swift
  iOS/Village/Village/Domain/Repository/ChatListRepository.swift
  iOS/Village/Village/Domain/UseCase/ChatListUseCase.swift
  iOS/Village/Village/Presentation/ChatList/View/ChatListTableViewCell.swift
  iOS/Village/Village/Presentation/ChatList/View/ChatListViewController.swift
  iOS/Village/Village/Presentation/ChatList/ViewModel/ChatListViewModel.swift
Labels: enhancement, iOS, chatting

#605 [BE/#599] userService 관심사 분리
  BE/src/app.module.ts
  BE/src/common/S3Handler.ts
  BE/src/entities/blockUser.entity.ts
  BE/src/entities/user.entity.ts
  BE/src/notification/notification.module.ts
  BE/src/notification/notification.service.spec.ts
  BE/src/notification/notification.service.ts
  BE/src/notification/registrationToken.repository.ts
  BE/src/post/post.module.ts
  BE/src/users/dto/usersUpdate.dto.ts
  BE/src/users/user.repository.ts
  BE/src/users/users.controller.ts
  BE/src/users/users.module.ts
  BE/src/users/users.service.ts
Labels: BE, environment

#607 [BE/#606] user service 테스트 코드 작성
  BE/src/users/users.controller.ts
  BE/src/users/users.service.spec.ts
  BE/src/users/users.service.ts
Labels: BE, environment

#604 [BE/#603] 채팅방 나갔다가 들어오면 이전 채팅 안보이게 구현
  BE/src/chat/chat.service.ts
  BE/src/entities/chatRoom.entity.ts
Labels: review, BE, chatting

#610 [BE/#609] 채팅 차단 확인 API
  BE/src/users-block/users-block.controller.ts
  BE/src/users-block/users-block.service.ts
Labels: review, BE, chatting
